source 'https://rubygems.org'

gem 'lerolero_generator'
gem 'cpf_utils'
gem 'nokogiri'

#pasta com ficam as Gems usadas em determinado trabhlo

#comando: 
#budle

## Ao rodar o bundle ele procura no Gemfile as dependências 
## e instala aquela que não tenha sido instalada